apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog
  name: blog
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: blog
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  labels:
    name: blog
spec:
  rules:
  - host: blog.info
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blog
            port: 
              number: 80
